export const uniListMock = [
  {
    name: "Concordia",
    deadline: "2021-12-31",
    applicationFee: "100",
    tuition: "10000",
    status: "good",
    coop: "yes",
    contact: "asd",
    fields: "asd",
    facultyResearch: "asd",
    gpa: "B+",
    preferenceForm: "asd",
    sop: "asd",
    cv: "asd",
    recom: "asd",
    transcript: "asd",
    toefl: "asd",
    feeEstimator: "asd",
  },
  {
    name: "Concordiaasdasdasd",
    deadline: "2021-12-qw31",
    applicationFee: "1002222",
    tuition: "10000",
    status: "good meh",
    coop: "yes",
    contact: "asd",
    fields: "asd",
    facultyResearch: "asd",
    gpa: "B+",
    preferenceForm: "asd",
    sop: "asd",
    cv: "asd",
    recom: "asd",
    transcript: "asd",
    toefl: "asd",
    feeEstimator: "asd",
  },
];

export const profListMock = [
  {
    name: "frank xxx",
    university: "Concordia",
    field: "immersive",
  },
  {
    name: "frank yyy",
    university: "Concordiaasdasdasd",
    field: "ai",
  },
];
